(function() {var implementors = {};
implementors["lettre"] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html' title='core::fmt::Display'>Display</a> for <a class='enum' href='lettre/transport/smtp/extension/enum.Extension.html' title='lettre::transport::smtp::extension::Extension'>Extension</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html' title='core::fmt::Display'>Display</a> for <a class='struct' href='lettre/transport/smtp/extension/struct.ServerInfo.html' title='lettre::transport::smtp::extension::ServerInfo'>ServerInfo</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html' title='core::fmt::Display'>Display</a> for <a class='enum' href='lettre/transport/smtp/authentication/enum.Mechanism.html' title='lettre::transport::smtp::authentication::Mechanism'>Mechanism</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html' title='core::fmt::Display'>Display</a> for <a class='enum' href='lettre/transport/smtp/response/enum.Severity.html' title='lettre::transport::smtp::response::Severity'>Severity</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html' title='core::fmt::Display'>Display</a> for <a class='enum' href='lettre/transport/smtp/response/enum.Category.html' title='lettre::transport::smtp::response::Category'>Category</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html' title='core::fmt::Display'>Display</a> for <a class='enum' href='lettre/transport/smtp/error/enum.Error.html' title='lettre::transport::smtp::error::Error'>Error</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html' title='core::fmt::Display'>Display</a> for <a class='enum' href='lettre/transport/stub/error/enum.Error.html' title='lettre::transport::stub::error::Error'>Error</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html' title='core::fmt::Display'>Display</a> for <a class='enum' href='lettre/transport/file/error/enum.Error.html' title='lettre::transport::file::error::Error'>Error</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html' title='core::fmt::Display'>Display</a> for <a class='enum' href='lettre/email/error/enum.Error.html' title='lettre::email::error::Error'>Error</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html' title='core::fmt::Display'>Display</a> for <a class='struct' href='lettre/email/struct.Email.html' title='lettre::email::Email'>Email</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
